# ===== SERVEUR =====
server.port=8081

# ===== SQLITE =====
spring.datasource.url=jdbc:sqlite:data/local.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ===== HIBERNATE =====
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== LOGS =====
logging.level.org.springframework=INFO
logging.level.com.newapp=DEBUG